# this container should be prepared for golang
language: go
go:
 - 1.10.2

# mongodb should be running
services: mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

# install all third party go packages that we use
install:
 - go get github.com/axw/gocov/...
 - go get github.com/AlekSi/gocov-xml

# Run all unittests sequentally in order to not push mongodb resources
script:
 - go test ./...
 - gocov test ./... 2> /dev/null | gocov report
