# this container should be prepared for golang
language: go

# mongodb should be running
services: mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

# install all third party go packages that we use
install:
 - go get github.com/gorilla/handlers
 - go get github.com/gorilla/mux
 - go get github.com/gorilla/context
 - go get github.com/stretchr/testify
 - go get gopkg.in/mgo.v2
 - go get gopkg.in/mgo.v2/bson
 - go get github.com/ARGOeu/go-lru-cache
 - go get gopkg.in/gcfg.v1
 - go get github.com/twinj/uuid
 - go get github.com/axw/gocov/...
 - go get github.com/AlekSi/gocov-xml
 - go get github.com/tools/godep

# Run all unittests sequentally in order to not push mongodb resources
script:
 - godep update ... # Using Godep.json update and create a local _workspace directory
 - gocov test ./... | gocov-xml > coverage.xml
