# this container should be prepared for golang
language: go

# mongodb should be running
services: mongodb

# install all third party go packages that we use
install:
 - go get github.com/gorilla/handlers
 - go get github.com/gorilla/mux
 - go get github.com/gorilla/context
 - go get github.com/stretchr/testify
 - go get labix.org/v2/mgo
 - go get labix.org/v2/mgo/bson
 - go get github.com/ARGOeu/go-lru-cache
 - go get code.google.com/p/gcfg

before_script:
# Standard mongodb 2.6 installation procedure (mongo docs)
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
# Wait a bit for mongod service to become available  
  - sleep 15 
# Check mongodb version
  - mongo --version

# Run all unittests sequentally in order to not push mongodb resources
script:
 - go test -v -p=1 ./...  
