site_name: Web Api documentation [V2]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/argo-web-api
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2015 GRNET S.A.

pages:
  - Home: index.md
  - Recomputations Requests: recomputations.md
  - Results : results.md
  - Status Results : status.md
  - Metric Profiles : metric_profiles.md
  - Aggregation Profiles : aggregation_profiles.md
  - Operations Profiles : operations_profiles.md
  - Reports : reports.md
  - Tenants : tenants.md
  - Error Codes: errors.md
  - Validation Checks: validations.md
  - Metrics: metrics.md

theme: readthedocs
